spring.application.name=transitpay-engine
spring.datasource.url=jdbc:mysql://localhost:3306/transitpay_db
spring.datasource.username=root
spring.datasource.password=admin2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true